@extends('layout.games')
@push('style')
    <style>
        .question-image {
            width: 300px;
            height: 300px;
            border-radius: 20px;
            object-fit: contain;
            border: 3px solid rgba(255,193,7,0.4);
        }
    </style>
@endpush
@section('content')
    <div class="game-container" style="margin-top: 8vh; z-index: 10;">
        <!-- Progress bar -->
        <div class="progress-bar-game mb-3">
            <div class="progress-fill" id="progressFill" style="width: 10%;"></div>
        </div>

        <!-- Header: Question number + Timer -->
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div id="questionNumber" class="timer-badge" style="font-size: 1.2rem; min-width: 90px; height: 50px;">1/10</div>
            <div id="timer" class="timer-badge" style="height: 50px; min-width: 70px; font-size: 1.4rem;">30</div>
        </div>

        <!-- Image + Question -->
        <div class="glass-card text-center mb-4" id="image_box">
            <img class="question-image mb-3" alt="">
            <div id="question_box">
                <h4 class="fw-bold text-danger mb-0">Potongan gambar pecahan uang berapakah ini?</h4>
            </div>
        </div>

        <!-- Options -->
        <style>
            .options-grid {
                display: grid;
                grid-template-columns: repeat(2, minmax(0, 1fr));
                gap: 1.25rem;
                width: 100%;
                position: relative;
                z-index: 20;
            }
            .options-grid .option-card {
                width: 100% !important;
                height: 72px !important;
                min-height: 72px !important;
                max-height: 72px !important;
                box-sizing: border-box !important;
                display: flex !important;
                align-items: center;
                justify-content: flex-start;
                padding: 0.75rem 1.25rem !important;
                background: rgba(255, 255, 255, 0.92) !important;
                border-radius: 16px;
                border: 2px solid rgba(255, 193, 7, 0.4);
                cursor: pointer;
                overflow: hidden;
                transition: background 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease !important;
                transform: none;
            }
            .options-grid .option-card span {
                font-size: 1.05rem;
                line-height: 1.3;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }
        </style>
        <div class="options-grid" id="optionsContainer">
            <!-- Generated by JS -->
        </div>
    </div>
@endsection

@push('script')
    <script>
        document.getElementById("musicController").addEventListener("click", () => {
            if (document.getElementById('musik').paused) {
                document.getElementById('logoMusic').classList.remove('fa-volume-xmark');
                document.getElementById('logoMusic').classList.add('fa-volume-high');
                document.getElementById('musik').play();
            } else {
                document.getElementById('logoMusic').classList.remove('fa-volume-high');
                document.getElementById('logoMusic').classList.add('fa-volume-xmark');
                document.getElementById('musik').pause();
            }
        });

        var question_box = document.querySelector('#question_box');
        var timers = document.querySelector('#timers');
        document.addEventListener('DOMContentLoaded', () => {
            gsap.from(
                '#image_box', {
                    scale: 0,
                    opacity: 0,
                    duration: 1,
                    ease: 'back.out'
                }
            );
        });

        let questions = [{
                images: [
                    "{{ asset('assets/uang/potongan/1000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_3.jpg') }}"
                ],
                answer: "Rp1000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/1000_TE00_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_TE00_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_TE00_3.jpg') }}"
                ],
                answer: "Rp1000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/1000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/1000_TE16_3.jpg') }}"
                ],
                answer: "Rp1000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/2000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_3.jpg') }}"
                ],
                answer: "Rp2000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/2000_TE09_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_TE09_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_TE09_3.jpg') }}"
                ],
                answer: "Rp2000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/2000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/2000_TE16_3.jpg') }}"
                ],
                answer: "Rp2000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/5000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_3.jpg') }}"
                ],
                answer: "Rp5000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/5000_TE01_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_TE01_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_TE01_3.jpg') }}"
                ],
                answer: "Rp5000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/5000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/5000_TE16_3.jpg') }}"
                ],
                answer: "Rp5000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/10000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_3.jpg') }}"
                ],
                answer: "Rp10000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/10000_TE05_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_TE05_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_TE05_3.jpg') }}"
                ],
                answer: "Rp10000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/10000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/10000_TE16_3.jpg') }}"
                ],
                answer: "Rp10000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/20000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_3.jpg') }}"
                ],
                answer: "Rp20000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/20000_TE04_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_TE04_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_TE04_3.jpg') }}"
                ],
                answer: "Rp20000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/20000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/20000_TE16_3.jpg') }}"
                ],
                answer: "Rp20000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/50000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_3.jpg') }}"
                ],
                answer: "Rp50000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/50000_TE05_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_TE05_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_TE05_3.jpg') }}"
                ],
                answer: "Rp50000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/50000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/50000_TE16_3.jpg') }}"
                ],
                answer: "Rp50000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/100000_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_3.jpg') }}"
                ],
                answer: "Rp100000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/100000_TE04_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE04_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE04_3.jpg') }}"
                ],
                answer: "Rp100000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/100000_TE14_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE14_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE14_3.jpg') }}"
                ],
                answer: "Rp100000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/100000_TE16_1.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE16_2.jpg') }}",
                    "{{ asset('assets/uang/potongan/100000_TE16_3.jpg') }}"
                ],
                answer: "Rp100000",
                type: "kertas"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/100.jpg') }}"
                ],
                answer: "Rp100",
                type: "logam"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/200.jpg') }}"
                ],
                answer: "Rp200",
                type: "logam"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/500.jpg') }}"
                ],
                answer: "Rp500",
                type: "logam"
            },
            {
                images: [
                    "{{ asset('assets/uang/potongan/1000.jpg') }}"
                ],
                answer: "Rp1000",
                type: "logam"
            }
        ];

        const optionsPool = {
            "Rp100": {
                correct: "Rp100",
                foreign_currency: ["$100", "€100", "¥100"],
                similar_nominal: ["Rp10", "Rp1000"],
                wrong_format: ["100Rp", "R100p"],
                different_nominal: ["Rp200", "Rp500", "Rp1000"]
            },
            "Rp200": {
                correct: "Rp200",
                foreign_currency: ["$200", "€200", "¥200"],
                similar_nominal: ["Rp20", "Rp2000"],
                wrong_format: ["200Rp", "R200p"],
                different_nominal: ["Rp100", "Rp500", "Rp1000"]
            },
            "Rp500": {
                correct: "Rp500",
                foreign_currency: ["$500", "€500", "¥500"],
                similar_nominal: ["Rp50", "Rp5000"],
                wrong_format: ["500Rp", "R500p"],
                different_nominal: ["Rp100", "Rp200", "Rp1000"]
            },
            "Rp1000": {
                correct: "Rp1000",
                foreign_currency: ["$1000", "€1000", "¥1000"],
                similar_nominal: ["Rp100", "Rp10000"],
                wrong_format: ["1000Rp", "R1000p"],
                different_nominal: ["Rp2000", "Rp5000", "Rp10000", "Rp500", "Rp200"]
            },
            "Rp2000": {
                correct: "Rp2000",
                foreign_currency: ["$2000", "€2000", "¥2000"],
                similar_nominal: ["Rp200", "Rp20000"],
                wrong_format: ["2000Rp", "R2000p"],
                different_nominal: ["Rp1000", "Rp5000", "Rp10000"]
            },
            "Rp5000": {
                correct: "Rp5000",
                foreign_currency: ["$5000", "€5000", "¥5000"],
                similar_nominal: ["Rp500", "Rp50000"],
                wrong_format: ["5000Rp", "R5000p"],
                different_nominal: ["Rp2000", "Rp10000", "Rp20000"]
            },
            "Rp10000": {
                correct: "Rp10000",
                foreign_currency: ["$10000", "€10000", "¥10000"],
                similar_nominal: ["Rp1000", "Rp100000"],
                wrong_format: ["10000Rp", "R10000p"],
                different_nominal: ["Rp5000", "Rp20000", "Rp50000"]
            },
            "Rp20000": {
                correct: "Rp20000",
                foreign_currency: ["$20000", "€20000", "¥20000"],
                similar_nominal: ["Rp2000", "Rp200000"],
                wrong_format: ["20000Rp", "R20000p"],
                different_nominal: ["Rp10000", "Rp50000", "Rp100000"]
            },
            "Rp50000": {
                correct: "Rp50000",
                foreign_currency: ["$50000", "€50000", "¥50000"],
                similar_nominal: ["Rp5000", "Rp500000"],
                wrong_format: ["50000Rp", "R50000p"],
                different_nominal: ["Rp20000", "Rp100000", "Rp10000"]
            },
            "Rp100000": {
                correct: "Rp100000",
                foreign_currency: ["$100000", "€100000", "¥100000"],
                similar_nominal: ["Rp10000", "Rp1000000"],
                wrong_format: ["100000Rp", "R100000p"],
                different_nominal: ["Rp50000", "Rp20000", "Rp1000"]
            }
        };

        let currentQuestionIndex = 0;
        let score = 0;
        const totalQuestions = 10;
        const timerDuration = {{ $timer }};
        let timer;
        let isAnswering = false;

        function startQuiz() {
            shuffleQuestions();
            startTimer();
            loadQuestion();
        }

        function shuffleQuestions() {
            const kertasQuestions = questions.filter(q => q.type === "kertas");
            const logamQuestions = questions.filter(q => q.type === "logam");

            kertasQuestions.sort(() => Math.random() - 0.5);
            logamQuestions.sort(() => Math.random() - 0.5);

            const selectedKertas = kertasQuestions.slice(0, 9);
            const selectedLogam = logamQuestions.slice(0, 1);

            questions = [...selectedKertas, ...selectedLogam];
            questions.sort(() => Math.random() - 0.5);
        }

        function updateProgress() {
            const pct = ((currentQuestionIndex + 1) / totalQuestions) * 100;
            document.getElementById('progressFill').style.width = pct + '%';
        }

        function loadQuestion() {
            isAnswering = false;
            if (currentQuestionIndex < totalQuestions) {
                updateProgress();
                const currentQuestion = questions[currentQuestionIndex];
                document.querySelector('#question_box h4').innerText =
                    currentQuestion.type === "logam" ?
                    "Uang logam berapakah ini?" :
                    "Potongan gambar pecahan uang berapakah ini?";

                const imageBox = document.querySelector('#image_box img');
                if (currentQuestion.type === "logam") {
                    imageBox.src = currentQuestion.images[0];
                } else {
                    const randomImageIndex = Math.floor(Math.random() * currentQuestion.images.length);
                    imageBox.src = currentQuestion.images[randomImageIndex];
                }

                const options = shuffleOptions(currentQuestion.answer, currentQuestion.type);

                const optionsContainer = document.getElementById('optionsContainer');
                optionsContainer.innerHTML = '';

                options.forEach((option, index) => {
                    const optionElement = document.createElement('div');
                    optionElement.className = 'option-card';
                    optionElement.dataset.value = option;
                    optionElement.innerHTML = `
                        <div class="rounded-circle d-flex justify-content-center align-items-center me-3 fw-bold" 
                             style="min-width: 40px; height: 40px; background: linear-gradient(135deg, #ffc107, #ffdb4d); color: #dc3545;">
                            ${String.fromCharCode(65 + index)}
                        </div>
                        <span class="fw-bold text-danger">${option}</span>
                    `;
                    optionElement.addEventListener('click', () => selectOption(option, optionElement));
                    optionsContainer.appendChild(optionElement);

                    gsap.from(optionElement, {
                        y: 15,
                        opacity: 0,
                        duration: 0.25,
                        ease: "power2.out",
                        delay: index * 0.05,
                        clearProps: "all"
                    });
                });

                document.getElementById('questionNumber').innerText = `${currentQuestionIndex + 1}/10`;

                gsap.from('#image_box', {
                    scale: 0.9,
                    opacity: 0,
                    duration: 0.4,
                    ease: "back.out"
                });
            } else {
                endQuiz();
            }
        }

        function shuffleOptions(correctAnswer, questionType) {
            const pool = optionsPool[correctAnswer];
            let distractors = [];

            const level = Math.floor(Math.random() * 4) + 1;

            if (questionType === "logam") {
                distractors = pool.different_nominal.filter(nom => {
                    const value = parseInt(nom.replace("Rp", ""));
                    return value <= 1000;
                });
                const foreign = pool.foreign_currency[Math.floor(Math.random() * pool.foreign_currency.length)];
                distractors = [foreign, ...distractors.slice(0, 2)];
            } else {
                if (level === 4) {
                    distractors = pool.different_nominal.slice(0, 3);
                } else if (level === 1) {
                    const foreign = pool.foreign_currency[Math.floor(Math.random() * pool.foreign_currency.length)];
                    distractors = [
                        foreign,
                        ...pool.different_nominal.slice(0, 2)
                    ];
                } else if (level === 2) {
                    const foreign = pool.foreign_currency[Math.floor(Math.random() * pool.foreign_currency.length)];
                    const wrongFormat = pool.wrong_format[Math.floor(Math.random() * pool.wrong_format.length)];
                    distractors = [
                        foreign,
                        wrongFormat,
                        pool.different_nominal[Math.floor(Math.random() * pool.different_nominal.length)]
                    ];
                } else if (level === 3) {
                    const foreign = pool.foreign_currency[Math.floor(Math.random() * pool.foreign_currency.length)];
                    const similar = pool.similar_nominal[Math.floor(Math.random() * pool.similar_nominal.length)];
                    const wrongFormat = pool.wrong_format[Math.floor(Math.random() * pool.wrong_format.length)];
                    distractors = [foreign, similar, wrongFormat];
                }
            }

            const options = [pool.correct, ...distractors];
            return options.sort(() => Math.random() - 0.5);
        }

        function selectOption(selectedOption, clickedElement) {
            if (isAnswering) return;
            isAnswering = true;
            
            const currentQuestion = questions[currentQuestionIndex];
            const isCorrect = selectedOption === currentQuestion.answer;

            if (isCorrect) {
                score++;
                clickedElement.classList.add('correct');
            } else {
                clickedElement.classList.add('wrong');
                // Highlight the correct answer
                document.querySelectorAll('.option-card').forEach(card => {
                    if (card.dataset.value === currentQuestion.answer) {
                        card.classList.add('correct');
                    }
                });
            }

            // Wait for feedback then move to next
            setTimeout(() => {
                currentQuestionIndex++;
                if (currentQuestionIndex < totalQuestions) {
                    loadQuestion();
                } else {
                    clearInterval(timer);
                    window.location.href = '/RupaRupiah/' + {{ $user_id }} + '/result/' + score;
                }
            }, 800);
        }

        function startTimer() {
            let timeLeft = timerDuration;
            const timerEl = document.getElementById('timer');
            timerEl.innerText = timeLeft;
            timer = setInterval(() => {
                if (timeLeft <= 0) {
                    clearInterval(timer);
                    endQuiz();
                } else {
                    timeLeft--;
                    timerEl.innerText = timeLeft;
                    if (timeLeft <= 5) {
                        timerEl.classList.add('urgent');
                    }
                }
            }, 1000);
        }

        function endQuiz() {
            Swal.fire({
                title: "Waktu Habis!",
                icon: "error",
                confirmButtonText: "Lihat Skor",
                background: '#ffffff',
                titleColor: '#dc3545',
                allowOutsideClick: false,
                allowEscapeKey: false,
                allowEnterKey: false,
                customClass: {
                    title: 'fw-bold text-danger',
                    popup: 'swal2-title-large',
                    confirmButton: 'btn-nusantara'
                },
                html: '<style>.swal2-title-large .swal2-title { font-size: 38px !important; }</style>'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = "/RupaRupiah/" + {{ $user_id }} + "/result/" + score;
                }
            });
        }

        document.addEventListener('DOMContentLoaded', startQuiz);
    </script>
@endpush